export const USER_LEVEL_SET = "USER_LEVEL_SET";

export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const UPDATE_ITEM_QUANTITY2 = "UPDATE_ITEM_QUANTITY2";
export const CLEAR_CART2 = "CLEAR_CART2";
export const EDIT_LENS_POWER = "EDIT_LENS_POWER";
